name       : flatpak
version    : 0.10.0
release    : 14
source     :
    - https://github.com/flatpak/flatpak/releases/download/0.10.0/flatpak-0.10.0.tar.xz : 57920502e154088e8a1776137e98786d53736daa92bb49c0920a0df1b7032da9
license    :
    - LGPL-2.0
    - LGPL-2.1
component  : desktop.util
summary    : Universal application support
description: |
    Linux application sandboxing and distribution framework
builddeps  :
    - pkgconfig(fuse)
    - pkgconfig(gtk-doc)
    - pkgconfig(json-glib-1.0)
    - pkgconfig(libarchive)
    - pkgconfig(libseccomp)
    - pkgconfig(libsoup-2.4)
    - pkgconfig(ostree-1)
    - pkgconfig(xau)
    - bubblewrap
    - docbook-xml
    - gpgme-devel
    - libassuan-devel
    - libcap2-devel
    - xmlto
rundeps    :
    - bubblewrap
setup      : |
    %configure --disable-static \
                --with-system-bubblewrap \
               --with-privileged-group=sudo \
               --with-profile-dir=/usr/share/defaults/etc/profile.d \
               --with-dbus-config-dir=/usr/share/dbus-1/system.d \
               --enable-gtk-doc \
               --enable-gtk-doc-html
build      : |
    %make
install    : |
    %make_install

    # Create the factory working tree
    install -D -d -m 00755 $installdir/usr/share/factory/var/lib/flatpak/repo
    install -d -m 00755 $installdir/usr/share/factory/var/lib/flatpak/repo/{extensions,objects}
    install -D -d -m 00755 $installdir/usr/share/factory/var/lib/flatpak/repo/refs/{heads,remotes}
    install -d -m 00755 $installdir/usr/share/factory/var/lib/flatpak/repo/state
    install -d -m 00755 $installdir/usr/share/factory/var/lib/flatpak/repo/tmp/cache
    touch $installdir/usr/share/factory/var/lib/flatpak/.changed

    cat << _EOF_ > $installdir/usr/share/factory/var/lib/flatpak/repo/config
    [core]
    repo_version=1
    mode=bare-user
    _EOF_

    # Now tell tmpfiles to create using factory
    install -D -m 00644 $pkgfiles/flatpak.tmpfiles $installdir/%libdir%/tmpfiles.d/flatpak.conf

    # support keyfile backend in flatpak
    install -m 00644 $pkgfiles/org.freedesktop.Flatpak.keyrules $installdir/usr/share/polkit-1/rules.d/.
