name       : flatpak
version    : 0.8.2
release    : 3
source     :
    - https://github.com/flatpak/flatpak/releases/download/0.8.2/flatpak-0.8.2.tar.xz : 2d9372f3d37374c14cbd55eac21ac3093c72bb7548b5fd0fac99a2bff85d8490
license    :
    - LGPL-2.0
    - LGPL-2.1
component  : desktop.util
summary    : Universal application support
description: |
    Linux application sandboxing and distribution framework
builddeps  :
    - pkgconfig(libarchive)
    - pkgconfig(libsoup-2.4)
    - pkgconfig(xau)
    - pkgconfig(fuse)
    - pkgconfig(json-glib-1.0)
    - pkgconfig(libseccomp)
    - pkgconfig(libelf)
    - pkgconfig(ostree-1)
    - docbook-xml
    - elfutils-devel
    - libcap2-devel
setup      : |
    %configure --disable-static \
               --with-privileged-group=sudo \
               --with-profile-dir=/usr/share/defaults/etc/profile.d \
               --with-dbus-config-dir=/usr/share/dbus-1/system.d
build      : |
    %make
install    : |
    %make_install

    # Create the factory working tree
    install -D -d -m 00755 $installdir/usr/share/factory/var/lib/flatpak/repo
    install -d -m 00755 $installdir/usr/share/factory/var/lib/flatpak/repo/{extensions,objects}
    install -D -d -m 00755 $installdir/usr/share/factory/var/lib/flatpak/repo/refs/{heads,remotes}
    install -d -m 00755 $installdir/usr/share/factory/var/lib/flatpak/repo/state
    install -d -m 00755 $installdir/usr/share/factory/var/lib/flatpak/repo/tmp/cache
    touch $installdir/usr/share/factory/var/lib/flatpak/.changed

    cat << _EOF_ > $installdir/usr/share/factory/var/lib/flatpak/repo/config
    [core]
    repo_version=1
    mode=bare-user
    _EOF_

    # Now tell tmpfiles to create using factory
    install -D -m 00644 $pkgfiles/flatpak.tmpfiles $installdir/%libdir%/tmpfiles.d/flatpak.conf
