name       : flatpak
version    : 1.12.4
release    : 53
source     :
    - https://github.com/flatpak/flatpak/releases/download/1.12.4/flatpak-1.12.4.tar.xz : 792e6265f7f6d71b2a087028472a048287bed2587e43d2eec2c31d360c16211c
license    : LGPL-2.1-or-later
component  : desktop
summary    : Universal application support
description: |
    Linux application sandboxing and distribution framework
builddeps  :
    - pkgconfig(appstream-glib)
    - pkgconfig(fuse)
    - pkgconfig(gpgme)
    - pkgconfig(gtk-doc)
    - pkgconfig(json-glib-1.0)
    - pkgconfig(libassuan)
    - pkgconfig(libcap)
    - pkgconfig(libseccomp)
    - pkgconfig(libsoup-2.4)
    - pkgconfig(ostree-1)
    - pkgconfig(xau)
    - bubblewrap
    - pyparsing
    - xmlto
rundeps    :
    - bubblewrap
    - xdg-desktop-portal
setup      : |
    %configure --disable-static \
        --with-dbus-config-dir=/usr/share/dbus-1/system.d \
        --with-privileged-group=sudo \
        --with-profile-dir=/usr/share/defaults/etc/profile.d \
        --with-system-bubblewrap \
        --with-system-helper-user=flatpak \
        --with-sysusersdir=%libdir%/sysusers.d/
build      : |
    %make
install    : |
    %make_install

    # Make sure that flatpak profile script is loaded after 10-xdg.sh
    mv $installdir/usr/share/defaults/etc/profile.d/flatpak.sh $installdir/usr/share/defaults/etc/profile.d/70-flatpak.sh

    # support keyfile backend in flatpak
    install -m00644 $pkgfiles/org.freedesktop.Flatpak.keyrules $installdir/usr/share/polkit-1/rules.d/.

