name       : flatpak
version    : 0.8.1
release    : 1
source     :
    - https://github.com/flatpak/flatpak/releases/download/0.8.1/flatpak-0.8.1.tar.xz : 9de103312b86f1033fa12768dc836525d6d9385defc80306e68691df66e7edaf
license    :
    - LGPL-2.0
    - LGPL-2.1
component  : desktop.util
summary    : Universal application support
description: |
    Linux application sandboxing and distribution framework
builddeps  :
    - pkgconfig(libarchive)
    - pkgconfig(libsoup-2.4)
    - pkgconfig(xau)
    - pkgconfig(fuse)
    - pkgconfig(json-glib-1.0)
    - pkgconfig(libseccomp)
    - pkgconfig(libelf)
    - pkgconfig(ostree-1)
    - docbook-xml
    - elfutils-devel
    - libcap2-devel
setup      : |
    %patch -p1 < $pkgfiles/0001-Support-a-stateless-configuration.patch
    %reconfigure --disable-static \
               --with-privileged-group=sudo
build      : |
    %make
install    : |
    %make_install
