name       : flatpak
version    : 1.14.4
release    : 63
source     :
    - https://github.com/flatpak/flatpak/releases/download/1.14.4/flatpak-1.14.4.tar.xz : 8a34dbd0b67c434e7598b98ec690953d046f0db26e480aeafb46d72aec716799
homepage   : https://flatpak.org/
license    : LGPL-2.1-or-later
component  : desktop
summary    : Universal application support
description: |
    Linux application sandboxing and distribution framework
builddeps  :
    - pkgconfig(appstream)
    - pkgconfig(fuse3)
    - pkgconfig(gdk-pixbuf-2.0)
    - pkgconfig(gpgme)
    - pkgconfig(gtk-doc)
    - pkgconfig(json-glib-1.0)
    - pkgconfig(libarchive)
    - pkgconfig(libassuan)
    - pkgconfig(libcap)
    - pkgconfig(libcurl)
    - pkgconfig(libseccomp)
    - pkgconfig(libzstd)
    - pkgconfig(ostree-1)
    - pkgconfig(xau)
    - bubblewrap
    - pyparsing
    - xmlto
rundeps    :
    - bubblewrap
    - xdg-desktop-portal
setup      : |
    NOCONFIGURE=1 %autogen
    %configure --disable-static \
        --enable-gtk-doc \
        --with-dbus-config-dir=/usr/share/dbus-1/system.d \
        --with-privileged-group=sudo \
        --with-profile-dir=/usr/share/defaults/etc/profile.d \
        --with-system-bubblewrap \
        --with-system-helper-user=flatpak \
        --with-sysusersdir=%libdir%/sysusers.d/
build      : |
    %make
install    : |
    %make_install

    # Make sure that flatpak profile script is loaded after 10-xdg.sh
    mv $installdir/usr/share/defaults/etc/profile.d/flatpak.sh $installdir/usr/share/defaults/etc/profile.d/70-flatpak.sh

    # Add tmpfiles
    install -Dm00644 $pkgfiles/flatpak.tmpfiles $installdir/%libdir%/tmpfiles.d/flatpak.conf
