name       : flatpak
version    : 1.10.3
release    : 46
source     :
    - https://github.com/flatpak/flatpak/releases/download/1.10.3/flatpak-1.10.3.tar.xz : 12723ad250997b5a28bef92ae632b097f50b0819feeb25ef8887fe8ec9b63b46
license    : LGPL-2.1-or-later
component  : desktop.util
summary    : Universal application support
description: |
    Linux application sandboxing and distribution framework
builddeps  :
    - pkgconfig(appstream-glib)
    - pkgconfig(fuse)
    - pkgconfig(gpgme)
    - pkgconfig(gtk-doc)
    - pkgconfig(json-glib-1.0)
    - pkgconfig(libassuan)
    - pkgconfig(libcap)
    - pkgconfig(libseccomp)
    - pkgconfig(libsoup-2.4)
    - pkgconfig(ostree-1)
    - pkgconfig(xau)
    - bubblewrap
    - pyparsing
    - xmlto
rundeps    :
    - bubblewrap
    - xdg-desktop-portal
setup      : |
    %configure --disable-static \
        --enable-gtk-doc \
        --enable-gtk-doc-html \
        --with-dbus-config-dir=/usr/share/dbus-1/system.d \
        --with-privileged-group=sudo \
        --with-profile-dir=/usr/share/defaults/etc/profile.d \
        --with-system-bubblewrap \
        --with-system-helper-user=flatpak \
        --with-sysusersdir=%libdir%/sysusers.d/
build      : |
    %make
install    : |
    %make_install

    # Make sure that flatpak profile script is loaded after 10-xdg.sh
    mv $installdir/usr/share/defaults/etc/profile.d/flatpak.sh $installdir/usr/share/defaults/etc/profile.d/70-flatpak.sh

    # Add tmpfiles
    install -D -m 00644 $pkgfiles/flatpak.tmpfiles $installdir/%libdir%/tmpfiles.d/flatpak.conf

    # support keyfile backend in flatpak
    install -m 00644 $pkgfiles/org.freedesktop.Flatpak.keyrules $installdir/usr/share/polkit-1/rules.d/.
