name       : flatpak
version    : 1.6.3
release    : 33
source     :
    - https://github.com/flatpak/flatpak/releases/download/1.6.3/flatpak-1.6.3.tar.xz : 5142f0ae48100f6af1fd43695a253a0a32d69b3280aff4d4f1ad93d61bb6489f
license    : LGPL-2.1-or-later
component  : desktop.util
summary    : Universal application support
description: |
    Linux application sandboxing and distribution framework
builddeps  :
    - pkgconfig(appstream-glib)
    - pkgconfig(fuse)
    - pkgconfig(gtk-doc)
    - pkgconfig(json-glib-1.0)
    - pkgconfig(libcap)
    - pkgconfig(libseccomp)
    - pkgconfig(libsoup-2.4)
    - pkgconfig(ostree-1)
    - pkgconfig(xau)
    - bubblewrap
    - gpgme-devel
    - libassuan-devel
    - xmlto
rundeps    :
    - bubblewrap
    - xdg-desktop-portal
setup      : |
    %configure --disable-static \
        --with-system-bubblewrap \
        --with-privileged-group=sudo \
        --with-profile-dir=/usr/share/defaults/etc/profile.d \
        --with-dbus-config-dir=/usr/share/dbus-1/system.d \
        --enable-gtk-doc \
        --enable-gtk-doc-html
build      : |
    %make
install    : |
    %make_install

    # Make sure that flatpak profile script is loaded after 10-xdg.sh
    mv $installdir/usr/share/defaults/etc/profile.d/flatpak.sh $installdir/usr/share/defaults/etc/profile.d/70-flatpak.sh

    # Add tmpfiles
    install -D -m 00644 $pkgfiles/flatpak.tmpfiles $installdir/%libdir%/tmpfiles.d/flatpak.conf

    # support keyfile backend in flatpak
    install -m 00644 $pkgfiles/org.freedesktop.Flatpak.keyrules $installdir/usr/share/polkit-1/rules.d/.

    # Add flatpak user
    install -D -m 00644 $pkgfiles/flatpak.sysusers $installdir/%libdir%/sysusers.d/flatpak.conf
