name       : flatpak
version    : 1.0.7
release    : 28
source     :
    - https://github.com/flatpak/flatpak/releases/download/1.0.7/flatpak-1.0.7.tar.xz : e0e6626a6d475ab263e7eab93d945d88f37c055fc9083d349101829b61253590
license    : LGPL-2.1-or-later
component  : desktop.util
summary    : Universal application support
description: |
    Linux application sandboxing and distribution framework
builddeps  :
    - pkgconfig(appstream-glib)
    - pkgconfig(fuse)
    - pkgconfig(gtk-doc)
    - pkgconfig(json-glib-1.0)
    - pkgconfig(libcap)
    - pkgconfig(libseccomp)
    - pkgconfig(libsoup-2.4)
    - pkgconfig(ostree-1)
    - pkgconfig(xau)
    - bubblewrap
    - gpgme-devel
    - libassuan-devel
    - xmlto
rundeps    :
    - bubblewrap
    - xdg-desktop-portal
setup      : |
    %configure --disable-static \
        --with-system-bubblewrap \
        --with-privileged-group=sudo \
        --with-profile-dir=/usr/share/defaults/etc/profile.d \
        --with-dbus-config-dir=/usr/share/dbus-1/system.d \
        --enable-gtk-doc \
        --enable-gtk-doc-html
build      : |
    %make
install    : |
    %make_install

    # Make sure that flatpak profile script is loaded after 10-xdg.sh
    mv $installdir/usr/share/defaults/etc/profile.d/flatpak.sh $installdir/usr/share/defaults/etc/profile.d/70-flatpak.sh

    # Add tmpfiles
    install -D -m 00644 $pkgfiles/flatpak.tmpfiles $installdir/%libdir%/tmpfiles.d/flatpak.conf

    # support keyfile backend in flatpak
    install -m 00644 $pkgfiles/org.freedesktop.Flatpak.keyrules $installdir/usr/share/polkit-1/rules.d/.
